# every VO sentence -> the exact screen content it must be matched to
BEATS=[
 dict(n=1,  vo=(121.20,129.40), say="one tap -> full game app published online",
      keys=["wave"], alt=["gold"], forbid=["publish app","settings","install grok"]),
 dict(n=2,  vo=(129.40,133.94), say="this is Grok on the phone, opened Grok Build",
      keys=["build apps and sites"], forbid=["thinking"]),
 dict(n=3,  vo=(135.88,142.74), say="lots of options, I picked Tower Defense",
      keys=["tower defense"], forbid=["thinking","cinderkeep"]),
 dict(n=4,  vo=(147.26,155.58), say="it started reading files already inside it",
      keys=["agents.md"], forbid=[]),
 dict(n=5,  vo=(155.58,162.94), say="not just a chatbot - a whole system behind the scenes",
      keys=["loading skill"], forbid=[]),
 dict(n=6,  vo=(162.94,168.12), say="then it spun up a sub-agent",
      keys=["agent running"], forbid=[]),
 dict(n=7,  vo=(168.12,174.96), say="and it was generating the game's images",
      keys=["imagine"], forbid=["can't generate","moderation"]),
 dict(n=8,  vo=(174.96,179.58), say="it worked - hit publish, chose the name",
      keys=["successfully published"], forbid=[]),
 dict(n=9,  vo=(183.86,189.68), say="also built a landing page, clean work",
      keys=["numbyai"], forbid=["thinking","conversation"]),
 dict(n=10, vo=(192.04,197.04), say="you can try Grok Build free today",
      keys=["wave"], alt=["gold"], forbid=["publish app","install grok"]),
 dict(n=11, vo=(213.88,222.48), say="cheapest plan - both apps ~7% of weekly usage",
      keys=["app builder","of total"], forbid=[]),
 dict(n=12, vo=(226.94,231.10), say="write Grok in the comments", keys=None),
]
